### ISSUE TITLE
If you modify an actor interface and add or revome methods the plugin needs renew proxies

### ISSUE THREAD

**Issue by daferpi** [eskatos/vlingo-gradle-plugin#4]
If you have a interface with methods and you add changes, adding or removing new methods, the plugin throw and error that the proxies already exist, but the desire behavior must be that the proxies needs to be remove and create again

**Comment by eskatos** [comment]
Thanks for the issue @daferpi.
Fixed in 74b17fdd0ebbae7adcb9f2e6906f8f1c4787fd8b
And published 0.1.1 to the plugin portal https://plugins.gradle.org/plugin/io.vlingo.codegen
